### ISSUE TITLE
Duplicate event with same commit ref and same commit message should be ignored

### ISSUE THREAD

**Issue by asfaltboy** [allenta/gitlab-listener#7] opened 2015-06-01 06:32 UTC
Currently if gitlab sends multiple events regarding same commit (i.e merged into another branch and so on), the plugin acts multiple times; and so `#refs ISSUE-999 #action resolve issue, fixed #time 20m` resolves issue, generates 2 identical comments and logs 40 minutes.

Perhaps this can be avoided if the plugin could somehow cache same commit/messages acted upon locally; maybe using a key such as a hash of the parsed `#ref` line and commit hash.

**Comment by carlosabalde** [comment] 2015-06-03 09:06
Thanks for the report. I'll check this and I'll get back to you asap.

**Comment by carlosabalde** [comment] 2015-06-03 13:22
A fix for this has been included in the latest version (v1.1.6), now [available in the Atlassian Marketplace](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b100100600). Please, update the add-on and let me know is the issue is fixed. Thanks!

**Closed as completed by carlosabalde** 2015-06-03 13:22 UTC
Labels: bug
